# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161011233113 on 2016-10-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Currency'),
        ),
    ]
