# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161011233113 on 2016-11-18 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rateditem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rateditem',
            table=None,
        ),
    ]
