# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161011233113 on 2016-10-21 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161021_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Replacement')),
            ],
        ),
        migrations.AddField(
            model_name='replacement',
            name='items',
            field=models.ManyToManyField(blank=True, through='catalog.ReplacementCatalog', to='catalog.Item'),
        ),
    ]
